export const dosenList = [
  {
    nama: "Muhammad Nur Ikhsan, S.Kom., M.Eng",
    foto: "/images/dosen/Muhammad Nur Ikhsan, S.T.,M.Eng.jpg",
    bidang: "Dekan Fakultas Teknik",
    kontak: "mnurikhsan@untara.ac.id",
    telepon: "", // Ganti dengan nomor asli (Gunakan format 62...)
  },
  {
    nama: "Saryani, S.Kom., M.TI",
    foto: "/images/dosen/Saryani.,S.Kom.,M.TI.webp",
    bidang: "Kaprodi Teknologi Informasi",
    kontak: "saryani@untara.ac.id",
    telepon: "6285310155710",
  },
  {
    nama: "Fabio Junior, S.Kom., M.Kom",
    foto: "/images/dosen/Fabio Junior.,S.Kom.,M.Kom.png",
    bidang: "Dosen Teknologi Informasi",
    kontak: "fabioj@untara.ac.id",
    telepon: "6281519576360",
  },
  {
    nama: "Irawan, S.Kom., M.Kom",
    foto: "/images/dosen/Irawan.,S.Kom.,M.Kom.png",
    bidang: "Dosen Teknologi Informasi",
    kontak: "irawan@untara.ac.id",
    telepon: "6281316556095",
  },
  {
    nama: "Kevin Septianzah, S.Kom., M.Kom",
    foto: "/images/dosen/Kevin Septianzah, S.Kom.,M.Kom..jpg",
    bidang: "Dosen Teknologi Informasi",
    kontak: "kevins@untara.ac.id",
    telepon: "628170713280",
  },
  {
    nama: "Septa Petriyansah, S.Kom., M.Kom",
    foto: "/images/dosen/Septa Febriyansyah.,S.M.,S.Kom.,M.Kom.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "septaf@untara.ac.id",
    telepon: "6282213038220",
  },
  {
    nama: "Amelia Sholikhaq, S.Kom., M.Kom",
    foto: "/images/dosen/Amelia Sholikhaq, S.Kom.,M.Kom.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "amelias@untara.ac.id",
    telepon: "628567808702",
  },
  {
    nama: "R Wahyudi Darmawan, ST., M.Kom",
    foto: "/images/dosen/R Wahyudi.,ST.,M.Kom.png",
    bidang: "Dosen Teknologi Informasi",
    kontak: "rwahyudi@untara.ac.id",
    telepon: "6281388264595",
  },
  {
    nama: "Ayi Khrisna, S.Kom., MM",
    foto: "/images/dosen/AYI KRISNHA W.A.N.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "ayikrisnha@untara.ac.id",
    telepon: "6287776151585",
  },
  {
    nama: "Ahmad Deni Muttaqin, S.Kom., M.Sc",
    foto: "/images/dosen/Ahmad Deni Muttaqin, S.Kom.,M.S.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "denim@untara.ac.id",
    telepon: "6289514038772",
  },
  {
    nama: "Rika Nurhidayah, S.Kom., M.Kom",
    foto: "/images/dosen/Rika Nurhidayah.,S.Kom.,MM.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "rikanurhidayah@untara.ac.id",
    telepon: "",
  },
  {
    nama: "Singgih Mitro, S.Kom., M.Kom",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "singgihm@untara.ac.id",
    telepon: "",
  },
  {
    nama: "Nisaul Khoiroh, S.Pd",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6281284521539",
  },
  {
    nama: "Diardana Prima Sintasari, M.Pd",
    foto: "/images/dosen/Diardana Prima Sintasari, M.Pd.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6285601821027",
  },
  {
    nama: "Faruq Haroky, M.Pd",
    foto: "/images/dosen/Faruq Haroky, M.Pd.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6285357608011",
  },
  {
    nama: "Dr.H.Suhada, S.Ag., M.Pd.I",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6281385743781",
  },
  {
    nama: "Fitri Anisa Kusumastuti, M.Pd",
    foto: "/images/dosen/Fitri Anisa Kusumastuti, M.Pd.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6285648687737",
  },
  {
    nama: "Novela Wulandari, M.Pd",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6282243437722",
  },
  {
    nama: "Rifa'atussalwa Hayati, M.Pd",
    foto: "/images/dosen/Rifa'atussalwa Hayati, M.Pd.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6285283828998",
  },
  {
    nama: "Febri Sari Siahaan, S.Kom., M.M",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6282292294845",
  },
  {
    nama: "Ahmad Roihan, S.Kom., MTI",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "6281387094383",
  },
  {
    nama: "Yani Sugiyani, S.Kom., M.Kom., MM",
    foto: "/images/dosen/Yani Sugiyani.,S.Kom.,M.Kom.,MM.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "",
  },
  {
    nama: "Syefri Maulana Husain, S.Kom., M.TI",
    foto: "/images/dosen/Syefri Maulana Husain.,S.Kom.,M.TI.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "",
  },
  {
    nama: "Dedi Gunawan, S.T., M.kom",
    foto: "/images/dosen/emot.webp",
    bidang: "Dosen Teknologi Informasi",
    kontak: "",
    telepon: "",
  },
];
